NTH-276-deploy-new-revision
Nortezh/nortezh-action pull request #1
Opened 2024-02-18 17:49 UTC by papapatcharakit

2024-02-18 17:49 UTC, K-Toshio commented
Task linked: [NTH-276 DevOps, Deploy new revision](https://app.clickup.com/t/42615263/NTH-276)

2024-02-21 11:47 UTC, xkamail requested changes

2024-02-21 11:47 UTC, xkamail commented on action.yml
> +  type: !!int
!!int อันนี้มันคือไรอะ

2024-02-21 11:47 UTC, xkamail commented on src/deployment.ts
> +    const credential = `${process.env["DEPLOYS_AUTH_USER"]}:${process.env["DEPLOYS_AUTH_PASS"]}`;
SA_AUTH_EMAIL
SA_AUTH_KEY
แทนได้ปะ

2024-02-21 11:47 UTC, xkamail commented on src/deployment.ts
> +      "https://api-stag-899570118063554590.nortezh0.deploys.app/user/deployment.get",
เก็บเป็น constant baseUrl แล้วเอามาต่อดีกว่า

2024-02-21 11:47 UTC, xkamail commented on src/index.ts
> +    if (error instanceof Error) core.setFailed(error.message);
เพิ่ม unknown error

2024-02-21 11:47 UTC, xkamail commented on src/types.ts
> +  DeployedByEmail: string;
deployedByEmail

2024-02-21 11:47 UTC, xkamail commented on src/types.ts
> +  StatusUrl: string;
statusUrl

2024-02-21 11:47 UTC, xkamail commented on src/types.ts
> +  id: number;
```suggestion
  id: string;
```

2024-02-21 11:47 UTC, xkamail commented on src/types.ts
> +  id: number;
มันจะได้เป็น string of integer

2024-02-21 11:47 UTC, xkamail commented on action.yml
> +    description: Project ID
ไม่ต้อง ID ก็ได้

2024-02-21 11:47 UTC, xkamail commented on action.yml
> +  public-url:
คิดว่าพวกนี้ใช้เป็น snake_case จะสวยกว่านะเวลาเขียน yaml

2024-02-21 12:02 UTC, papapatcharakit commented on action.yml
> +  type: !!int
ติดมาจากสักที ลบและ

2024-02-21 12:50 UTC, papapatcharakit commented on action.yml
> +  public-url:
แต่ส่วนใหญ่เราก็เห็นใช้ kebab case นะ @xkamail

2024-02-21 13:30 UTC, xkamail approved these changes

2024-02-21 13:30 UTC, merged